### ISSUE TITLE
Tickets gewinnen wird nicht automatisch ausgewählt

### ISSUE THREAD

**Issue by drenica92** [ggmanugg/energyair_bot#12]
Jetzt Tickets gewinnen wird nicht automatisch ausgewählt. Man muss es selber anklicken. File wurde mehrmals neu installiert.

**Comment by ggmanugg** [comment]
Welches der beiden Scripte benutzt du?

**Comment by drenica92** [comment]
Ich benutze diesen Script; energyairbot_recaptcha.user.js

**Comment by ggmanugg** [comment]
Kann den Fehler leider nicht reproduzieren. Bei mir werden die Tickets ausgewählt. Versuche es mal mit einem anderen Browser.

**Comment by ggmanugg** [comment]
Habe das README entsprechend aktualisiert. Ganz umgehen kann man es wohl nicht.
