### ISSUE TITLE
Energy Air 

### ISSUE THREAD

**Issue by drenica92** [ggmanugg/energyair_bot#13]
Es kommt sehr oft diese Fehlermeldung im Browser (Firefox, Chrome) : 
Es tut uns leid, aber Ihr Computer oder Netzwerk sendet möglicherweise automatisierte Anfragen. Zum Schutz unserer Benutzer können wir Ihre Anfrage derzeit nicht bearbeiten.

Kann man etwas dagegen tun?

PS: Vielen Dank für deine tolle Arbeit!

**Comment by generalxhd** [comment]
Bei mir kommt das nach ungefähr 4 Stunden. 
Schliesse einfach den Tab für 10 Minuten und starte dann das Game erneut.
