### ISSUE TITLE
Ticketauswahl

### ISSUE THREAD

**Issue by SaschaBZ** [ggmanugg/energyair_bot#17]
Re-Captcha funktioniert perfekt, auch das Spiel spielt es super durch. 
Nur bei der Ticketauswahl bleibt er einfach stehen. 
Firefox blockt dann über 100 Pop-ups, werden die Erlaubt, füllt sich der Browser mit Werbung. 
Zur Bubbelauswahl komme ich erst durch manuelles klicken.

**Comment by ggmanugg** [comment]
Hatte das Problem auch mal Zwischendurch. Cookies und alle andere Browserdaten löschen hat bei mir geholfen.

Warten wir bis auf das nächste Jahr :)

**Comment by SaschaBZ** [comment]
Herzlichen Dank ;) 

 
 

Gesendet: Dienstag, 07. September 2021 um 08:40 Uhr
Von: "Manuel Berger" ***@***.***>
An: "ggmanugg/energyair_bot" ***@***.***>
Cc: "SaschaBZ" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ggmanugg/energyair_bot] Ticketauswahl (#17)


 

Hatte das Problem auch mal Zwischendurch. Cookies und alle andere Browserdaten löschen hat bei mir geholfen.

Warten wir bis auf das nächste Jahr :)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
