### ISSUE TITLE
Other logo

### ISSUE THREAD

**Issue by Rowside** [ggmanugg/energyair_bot#2]
Hello

Question

Can we Edit am Other Logo ? I think about and to 24 H  Computer i have never win

**Comment by Rowside** [comment]
Hallo

Habe eine frage

könntest du das umscripten das irgend wie jede 5 Minuten das Logo wächselt das funktioniert irgend wie nicht bei mir

**Comment by ggmanugg** [comment]
Hallo

Es spielt keine Rolle, welches Logo das Script auswählt.
Der Server entscheidet nur zwischen gewonnen oder verloren. Nicht, ob du das richtige Logo ausgewählt hast.

Lg
