### ISSUE TITLE
Updated the Bot to the 2021 Game

### ISSUE THREAD

**Issue by LuckLP** [ggmanugg/energyair_bot#6]
I updated the Bot to the 2021 Game and want to push to a new branch.

**Comment by RoadJDK** [comment]
Have fun waiting for the repo owner to response (Pretty much a dead account)
Just fork the repository and change it there

**Comment by alextruong2600** [comment]
I also have updated the Bot to the 2021 Game. If you want to use it, just use this link: https://github.com/alextruong2600/energyairbot2021

**Comment by LuckLP** [comment]
> Have fun waiting for the repo owner to response (Pretty much a dead account)
> Just fork the repository and change it there

Yeah, I thought so.



> I also have updated the Bot to the 2021 Game. If you want to use it, just use this link: https://github.com/alextruong2600/energyairbot2021

Thanks for that.
